# Copyright (c) 2017-2019, Substratum LLC (https://substratum.net) and/or its affiliates. All rights reserved.
FROM rust:latest

WORKDIR /test_root/dns_utility
CMD ["bash", "-c", "$(pwd)/ci/run_integration_tests.sh"]
