name: ci-matrix

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ matrix.os }}
      run: |
        rustup show
        cargo version
        sudo systemctl disable systemd-resolved.service
        sudo service systemd-resolved stop
        echo "*********"
        cat /etc/NetworkManager/NetworkManager.conf
        echo "*********"
        sudo sed -i "s/^dns=.*$/dns=default/g" /etc/NetworkManager/NetworkManager.conf
        echo "*********"
        cat /etc/resolv.conf
        echo "*********"
        ./ci/all.sh
      shell: bash
