name: ci-matrix

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - name: Build ${{ matrix.os }}
      run: |
        netstat -ano
        net stop W3svc
        netstat -ano
      shell: cmd
