name: ci-matrix

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ matrix.os }}
      run: |
        rustup show
        cargo version
        sudo echo DNSStubListener=no >> /etc/systemd/resolved.conf
        sudo systemctl daemon-reload
        sudo systemctl restart systemd-resolved.service
        ./ci/all.sh
      shell: bash
