name: ci-matrix
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Build ${{ matrix.os }}
      run: cat /etc/docker/daemon.json
      shell: bash
