name: ci-matrix
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
    - name: Build ${{ matrix.os }}
      run: |
        env
        [[ $GITHUB_ACTIONS ]] && echo "Just $GITHUB_ACTIONS alone"
        [[ $GITHUB_ACTIONS -eq true ]] && echo "Bare true"
        [[ $GITHUB_ACTIONS -eq 'true' ]] && echo "Single quoted true"
        [[ $GITHUB_ACTIONS -eq "true" ]] && echo "Double quoted true"
        [[ -f /etc/docker/daemon.json ]] && cat /etc/docker/daemon.json
        [[ ! -f /etc/docker/daemon.json ]] && echo "/etc/docker/daemon.json not found"
      shell: bash
