name: ci-matrix

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build ${{ matrix.os }}
      run: |
        rustup show
        cargo version
        cat /etc/resolv.conf
        sudo rm -f /etc/resolv.conf
        sudo echo "nameserver 1.1.1.1" >> /etc/resolv.conf
        ./ci/all.sh
      shell: bash
